import type { Metadata } from 'next';
import { Josefin_Sans } from 'next/font/google';
import React from 'react';
import './globals.css';
import { ThemeProvider } from 'next-themes';

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  variable: '--font-josefin-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${josefinSans.variable} font-sans`}
      >
        <ThemeProvider enableSystem={false} defaultTheme='dark'>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
